version: '2.4'
services:
  ntsimulator-o-ran-sc:
    image: "o-ran-sc/ntsim-manager:latest"
    #image: "10.20.6.10:30000/hightec/ntsim_manager:0.4.2-SNAPSHOT-latest"
    container_name: NTS-Manager-o-ran-sc
    ports:
     - "::8300:830"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/var/tmp/NTS-Manager-o-ran-sc:/opt/dev/scripts"
     - "/usr/bin/docker:/usr/bin/docker"
    labels:
      "NTS-manager": ""
    environment:
      #NTS_IP: "2001:db8:1::1"
      NTS_IP: "10.20.11.121"
      #EXTERNAL_NTS_IP: "8.8.8.8"
      NETCONF_BASE: 50000
      DOCKER_ENGINE_VERSION: "1.40"
      #MODELS_IMAGE: "ntsim_onf_core_model_1_2"
      MODELS_IMAGE: "o-ran-sc/ntsim-o-ran-ru-fh:latest"      
      VesHeartbeatPeriod: 0
      IsVesAvailable: "true"
      IsNetconfAvailable: "true"
      VesRegistration: "false"
      VesEndpointPort: 8080
      VesEndpointIp: "172.17.0.1"
      VesEndpointAuthMethod: "basic-auth"
      VesEndpointUsername: "sample1"
      VesEndpointPassword: "sample1"
      SshConnections: 1
      TlsConnections: 0
      K8S_DEPLOYMENT: "false"
      CONTAINER_NAME: "nts-o-ran-sc"
      NetconfCallHome: "false"
      NetconfCallHomePort: 6666
      ControllerIp: "10.20.11.121"
      ControllerPort: 8181
      ControllerUsername: "admin"
      ControllerPassword: "admin"
      IPv6Enabled: "true"
    networks:
      app_net:
        ipv6_address: 2001:3200:3000::40
  
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3000::/64
          gateway: 2001:3200:3000::1